2024-02-05 10:15:09.648654: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/luker/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
Alpaca orders
Empty DataFrame
Columns: []
Index: []
Exception occurred: 
[Errno 104] Connection reset by peer
Counts for buy, sell, hold:  [0, 0, 0]
Traceback (most recent call last):
  File "/home/luker/anaconda3/envs/trading_env/bin/bot", line 8, in <module>
    sys.exit(main())
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/bot/cli/bot.py", line 26, in main
    bot.start()
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/bot/bot.py", line 166, in start
    plt = plotAlpaca(dt.date(2024,2,5), self.API_KEY, self.API_SECRET) # pylint: disable=no-value-for-parameter
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/bot/plotAlpaca.py", line 100, in plotAlpaca
    spFirst = spList[0]
IndexError: list index out of range
